# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: CHILDREN INTERNATIONAL
# Description of the Site
description: CAMBIALE LA VIDA A UN NIÑO DE ESCASOS RECURSO
# URL of Image of the Site
site-image: /WhatATheme/assets/images/portada.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: thedevslot@gmail.com
facebook_username: thedevslot
twitter_username: thedevslot
instagram_username: thedevslot
linkedin_username: thedevslot
github_username:  thedevslot
youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow


# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: TheDevsLot
# URL for the Image of the Author
author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: Al crecer en situaciones de pobreza, los niños enfrentan grandes grandes obstaculos como son el hambre y desnutrición, acceso limitado a educación y servicios médicos, discriminación social y aislamiento. Sin embargo, con el apoyo de personas como usted, podemos ayudar a que los niños reciban la atención médica, educación, habilidades para la vida, formación laboral y confianza que necesitan para generar un cambio positivo y duradero en sus vidas y comunidades. Juntos, podemos acabar con la pobreza para siempre.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
